apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mongodb

spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:4.4
        ports: 
        - containerPort: 27017


---

apiVersion: v1
kind: Service
metadata:
  name: service-mongodb # ce nom de service est associé à une résolution DNS au serveur
spec:
  type: ClusterIP
  selector: 
    app: mongodb
  ports:
  - port: 27017 #port du service (proxy)
    targetPort: 27017 # port des pods du déploiement
    protocol: TCP